name: Coveros Copilot Onboarding
description: Fill out this form to request access to the Organization and to be assigned a Copilot License
title: Onboarding Request
labels: ["onboarding"]
body:
  - type: input
    id: access_code
    attributes:
      label: ">>Access Code<<"
      description: Please input the access code given to you by Coveros
    validations:
      required: true
